sport/urls.py
from django.urls import path
from . import views

app_name = 'sport'

urlpatterns = [
    path('', views.home, name='home'),
    
    path('index/', views.index, name='index'),

    path('<int:tr_sport_id>/', views.detail, name ='detail'),

    path('<int:trainer_id>/detail_trainer/', views.detail_trainer, name='detail_trainer'),

    path('<int:sport_id>/detail_not_user/', views.detail_not_user, name ='detail_not_user'),

    path('schedule/', views.schedule, name ='schedule'),

    path('financial_status/', views.financial_status, name ='financial_status'),

    path('medical_report/', views.medical_report, name ='medical_report'),

    path('add_sport/', views.add_sport, name ='add_sport'),

    path('<int:tr_sport_id>/delete_sport', views.delete_sport, name ='delete_sport'),
    
    path('register/', views.register, name ='register'),
    
    path('login_user/', views.login_user, name ='login_user'),
    
    path('logout_user/', views.logout_user, name ='logout_user'),
]

sportsclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sport.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sport/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Permission, User



class Session(models.Model):
    session = models.CharField(max_length=20)

    def __str__(self):
        return self.session



class Day(models.Model):
    day_name = models.CharField(max_length=20)

    def __str__(self):
        return self.day_name



class Sport(models.Model):
    sport_name = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    fee = models.FloatField()
    max_capacity = models.IntegerField()
    current_capacity = models.IntegerField(default=0)
    days = models.ManyToManyField(Day)
    sport_logo = models.FileField(null=True)

    def __str__(self):
        return self.sport_name
   

class SportSessionCapacity(models.Model):
    sport = models.ForeignKey(Sport, on_delete = models.CASCADE)
    session = models.ForeignKey(Session, on_delete = models.CASCADE)
    session_max_cap = models.IntegerField(null=True, blank=True)
    session_current_cap = models.IntegerField(default=0,null=True, blank=True) 

    def __str__(self):
        return str(self.sport) + '-' +str(self.session) + "- capacity"


class TraineeSport(models.Model):
    user = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
    sport = models.ForeignKey(Sport, on_delete = models.CASCADE)
    session_choice = models.ForeignKey(Session, on_delete = models.CASCADE)
    is_paid = models.BooleanField(default = False)

    def __str__(self):
        return str(self.user) + ' - ' + str(self.sport)



class Trainer(models.Model):
    trainer_name = models.CharField(max_length=100)
    sport = models.ForeignKey(Sport, on_delete = models.CASCADE)
    sessions = models.ManyToManyField(Session)
    phone_number = models.CharField(max_length=11, null=False, unique=True)
    date_of_birth = models.DateField()
    trainer_photo = models.FileField(null=True)

    def __str__(self):
        return self.trainer_name + '-' + str(self.sport)




class MedicalReport(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,)
    height = models.IntegerField()
    gender_choices = (('M', 'Male'), ('F', 'Female'))
    gender = models.CharField(max_length=6, choices=gender_choices)
    weight = models.IntegerField()
    fat_percentage = models.FloatField()
    muscle_percentage = models.FloatField()
    disease = models.TextField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return str(self.user) + " -  Medical report "

sport/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Sport, TraineeSport

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class AddSportForm(forms.ModelForm):

    class Meta:
        model = TraineeSport
        fields = ['sport', 'session_choice']

sport/views.py
from .forms import UserForm, AddSportForm
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .models import Sport, TraineeSport, Day, MedicalReport, Trainer, SportSessionCapacity
from datetime import date



def home(request):
    all_sports = Sport.objects.all()

    if not request.user.is_authenticated:
        return render(request, 'sport/home_not_user.html', {'all_sports': all_sports})

    return render(request, 'sport/home_user.html', {'all_sports': all_sports})



def index(request):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')
    else:
        tr_sport = TraineeSport.objects.filter(user=request.user)
        sport = Sport.objects.all()
        query = request.GET.get("q")
        if query:
            try:
                sport = sport.get(sport_name__icontains=query)
            except:
                return render(request, 'sport/index.html', {'tr_sport': tr_sport})
            
            trainers = Trainer.objects.filter(sport=sport)
            return render(request, 'sport/detail_not_user.html', {'sport': sport, 'trainers': trainers})

        return render(request, 'sport/index.html', {'tr_sport': tr_sport})



def detail(request, tr_sport_id):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')
    else:
        tr_sport = get_object_or_404(TraineeSport, pk=tr_sport_id)
        trainers = Trainer.objects.filter(sport = tr_sport.sport)
        context = {
            'tr_sport': tr_sport,
            'trainers': trainers,
        }
        return render(request, 'sport/detail.html', context)



def detail_trainer(request, trainer_id):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')

    trainer = get_object_or_404(Trainer, pk=trainer_id)
    today = date.today()
    age = today.year - trainer.date_of_birth.year - ((today.month, today.day) < (trainer.date_of_birth.month, trainer.date_of_birth.day))
    return render(request, 'sport/detail_trainer.html', {'trainer': trainer, 'age': age})



def detail_not_user(request, sport_id):
    sport = get_object_or_404(Sport, pk=sport_id)
    trainers = Trainer.objects.filter(sport=sport)
    return render(request, 'sport/detail_not_user.html', {'sport': sport, 'trainers':trainers})


def schedule(request):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')
    else:
        tr_sport = TraineeSport.objects.filter(user=request.user)
        all_days = Day.objects.all()
        return render(request, 'sport/schedule.html', {'tr_sport': tr_sport, 'all_days': all_days,})


def financial_status(request):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')
    
    tr_sports = TraineeSport.objects.filter(user=request.user, is_paid=False)
    tot_fee = tr_sports.aggregate(total_fee=Sum('sport__fee'))
    total_fee = tot_fee['total_fee']
    return render(request, 'sport/financial_status.html', {'tr_sports': tr_sports, 'total_fee': total_fee})


def medical_report(request):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')
    try:
        med_rep = MedicalReport.objects.get(user=request.user)
    except:
        return render(request, 'sport/medical_report.html')

    return render(request, 'sport/medical_report.html', {'med_rep': med_rep,})






def add_sport(request):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')

    else:
        form = AddSportForm(request.POST or None)
        exsist_sports = TraineeSport.objects.filter(user=request.user)

        if form.is_valid():

            chosen_sport = Sport.objects.get(sport_name=form.cleaned_data.get("sport"))
            if chosen_sport.current_capacity == chosen_sport.max_capacity:
                context = {
                        "form": form,
                        'error_message': 'There Is No Current Available Places In This Sport!',
                     }
                return render(request, 'sport/add_sport.html', context)
            
            #try:
                chosen_session = SportSessionCapacity.objects.get(session=form.cleaned_data.get("session_choice"),sport=chosen_sport)
            #except:
                context = {
                        "form": form,
                        'error_message': 'This Session is not Available for this sport!',
                     }
                return render(request, 'sport/add_sport.html', context)
            #chosen_session.session_max_cap = chosen_sport.max_capacity // 5



            #if chosen_session.session_max_cap == chosen_session.session_current_cap:
                context = {
                        "form": form,
                        'error_message': 'There Is No Current Available Places In This Session Try another Session!',
                     }
                return render(request, 'sport/add_sport.html', context)


            for ex_sp in exsist_sports:
                if ex_sp.sport == form.cleaned_data.get("sport"):
                    context = {
                        "form": form,
                        'error_message': 'You Are Already Subscribed To This Sport!',
                     }
                    return render(request, 'sport/add_sport.html', context)
                
                if ex_sp.session_choice == form.cleaned_data.get("session_choice"):
                    for day in ex_sp.sport.days.all():
                        if day in chosen_sport.days.all():
                            context = {
                                "form": form,
                                'error_message': 'This Session is not Compatible with Your Schedule!',
                            }
                            return render(request, 'sport/add_sport.html', context)

            chosen_sport.current_capacity += 1
            #chosen_session.session_current_cap += 1
            chosen_sport.save()

            tr_sport = form.save(commit=False)
            tr_sport.user = request.user
            tr_sport.save()
            return render(request, 'sport/detail.html', {'tr_sport': tr_sport})

        context = {
            "form": form,
        }
        return render(request, 'sport/add_sport.html', context)



    


def delete_sport(request, tr_sport_id):
    if not request.user.is_authenticated:
        return render(request, 'sport/login.html')

    tr_sp = TraineeSport.objects.get(pk=tr_sport_id)
    if tr_sp not in TraineeSport.objects.filter(user=request.user):
        tr_sport = TraineeSport.objects.filter(user=request.user)
        return render(request, 'sport/index.html', {'tr_sport': tr_sport})
    tr_sp.delete()
    tr_sport = TraineeSport.objects.filter(user=request.user)
    return render(request, 'sport/index.html', {'tr_sport': tr_sport})
   


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'sport/index.html', {})
    context = {
        "form": form,
    }
    return render(request, 'sport/register.html', context)



def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                tr_sport = TraineeSport.objects.filter(user=request.user)
                return render(request, 'sport/index.html', {'tr_sport': tr_sport})
            else:
                return render(request, 'sport/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'sport/login.html', {'error_message': 'Invalid login'})
    return render(request, 'sport/login.html')



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'sport/login.html', context)

sport/templates/sport/add_sport.html
{% extends 'sport/base.html' %}
{% block title %}Add a New Sport{% endblock %}
{% block add_sport_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Sport</h3>
                    {% if error_message %}
                        <p class="text-danger"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'sport/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Sporting?</h3>
                    <p>Sporting is a Website that allow you to Subscribe to any Sport in the Club Online.</p>
                    <h3>How do I Subscribe to a Sport?</h3>
                    <p>First, you need to <a href="{% url 'sport:register' %}">Register</a> in to create a New Account or <a href="{% url 'sport:login_user' %}">Login</a> if you already have one. Then, click <a href="{% url 'sport:add_sport' %}">Add Sport</a> and choose the Sport and Session you want from the Form that will appear.</p>
                    <h3>What are some other Facilities at Sporting?</h3>
                    <ul>
                        <li>You can view the Details about each Sport you are Subscribed to.</li>
                        <li>You can view your Schedule all along the Week.</li>
                        <li>You can view your Medical Report.</li>
                        <li>You can Look up your Financial Status.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

sport/templates/sport/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sporting{%endblock%}</title>
    
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'sport/style.css' %}"/>
    <script src="https://kit.fontawesome.com/66d9cd80a7.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
         <div class="container-fluid"> 
             
             <div class="navbar-header">
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                 </button>    
                 <a class="navbar-brand" href="{% url 'sport:home' %}">                     
                    <span class="fas fa-running"  aria-hidden="true"></span>&nbsp; Sporting
                 </a>
             </div>
             
             
             <div class="collapse navbar-collapse" id="topNavBar">
             
                 <ul class="nav navbar-nav">
                     <li class="{% block sports_active %}{% endblock %}">
                         <a href="{% url 'sport:index' %}">
                             <span class="fas fa-futbol"  aria-hidden="true"></span>&nbsp; My Sports
                         </a>
                     </li> 
                     
                     <li class="{% block schedule_active %}{% endblock %}">
                         <a href="{% url 'sport:schedule' %}">
                             <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp; Schedule
                         </a>
                     </li>
                 </ul>
                 
                 
                 <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'sport:index' %}">
                     <div class="form-group">
                         <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                     </div>
                     <button type="submit" class="btn btn-default">search</button>
                 </form>
                 
                 
                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block financial_status_active %}{% endblock %}">
                        <a href="{% url 'sport:financial_status' %}">
                            <span class="fas fa-dollar-sign" aria-hidden="true"></span>&nbsp; Status
                        </a>
                    </li>

                    <li class="{% block medical_report_active %}{% endblock %}">
                        <a href="{% url 'sport:medical_report' %}">
                            <span class="fas fa-stethoscope" aria-hidden="true"></span>&nbsp; Med Rep
                        </a>
                    </li>

                    <li class="{% block add_sport_active %}{% endblock %}">
                        <a href="{% url 'sport:add_sport' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Sport
                        </a>
                    </li>
                     
                    <li class="">
                        <a href="{% url 'sport:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
                 
             </div>
             
             
         </div>
    </nav>
        {% block body%}
        {%endblock%}

</body>
</html>

sport/templates/sport/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sporting{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <script src="https://kit.fontawesome.com/66d9cd80a7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'sport/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'sport:home' %}">
                <span class="fas fa-running"  aria-hidden="true"></span>&nbsp; Sporting
            </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}">
                    <a href="{% url 'sport:register' %}">
                        <span class="fas fa-registered"  aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="{% block login_active %}{% endblock %}">
                    <a href="{% url 'sport:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Log In
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

sport/templates/sport/detail.html
{% extends 'sport/base.html' %}
{% block title %}{{ tr_sport }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="">
                        {% if tr_sport.sport.sport_logo %}
                            <img src="{{ tr_sport.sport.sport_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'sport:schedule' %}">View Schedule</a></li>
                <li role="presentation"><a href="{% url 'sport:add_sport'%}">Add New Sport</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>{{ tr_sport.user }} - {{ tr_sport.sport }}</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Sport</th>
                            <th>Location</th>
                            <th>Session</th>
                            <th>Days</th>
                            <th>Trainers</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        
                        <tbody>
                        <tr>
                            <td>{{ tr_sport.sport }}</td>
                            <td>{{ tr_sport.sport.location }}</td>
                            <td>{{ tr_sport.session_choice }}</td>
                            <td style="color:green">
                                {% for day in tr_sport.sport.days.all %}
                                    {{ day }}<br>
                                {%endfor%}
                            </td>
                            <td>
                                {% for trainer in trainers %}
                                    {% for session in trainer.sessions.all %}
                                        {%if session == tr_sport.session_choice%}
                                        <a href="{% url 'sport:detail_trainer' trainer.id%}">{{trainer}}</a><br>
                                        {%endif%}
                                    {%endfor%}
                                {%endfor%}
                            </td>
                            <td>
                                <form action="{% url 'sport:delete_sport' tr_sport.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="tr_sport_id" value="{{ tr_sport.id }}" />
                                    <button type="submit" class="btn btn-danger btn-xs">
                                        <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete Sport
                                    </button>
                                </form>
                            </td>
                        </tr>
   
                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

sport/templates/sport/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

sport/templates/sport/home_not_user.html
{% extends 'sport/base_visitor.html' %}

{% block body %}
{% include 'sport/home_template.html' %}
{% endblock %}

sport/templates/sport/home_template.html
<div class="sports-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h1><strong>Welcome to Sporting!</h1></strong>
            <h3>What is Sporting?</h3>
            <p>Sporting is a Website that allow you to Subscribe to any Sport in the Club Online.</p>
            <h3>How do I Subscribe to a Sport?</h3>
            <p>First, you need to <a href="{% url 'sport:register' %}">Register</a> in to create a New Account or <a href="{% url 'sport:login_user' %}">Login</a> if you already have one. Then, click <a href="{% url 'sport:add_sport' %}">Add Sport</a> and choose the Sport and Session you want from the Form that will appear.</p>
            <h3>What are some other Facilities at Sporting?</h3>
            <ul>
                <li>You can view the Details about each Sport you are Subscribed to.</li>
                <li>You can view your Schedule all along the Week.</li>
                <li>You can view your Medical Report.</li>
                <li>You can Look up your Financial Status.</li>
            </ul>
        </div>
        
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 style="color:rgba(4, 0, 255, 0.664)";><strong>Sports That We Provide:</strong></h3>
                    
                    {% for sport in all_sports %}
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">
                            <a href="{% url 'sport:detail_not_user' sport.id%}">
                                <img src="{{ sport.sport_logo.url }}" class="img-responsive" style="width: 250px";>
                            </a>
                            <div class="caption">
                                <h2>{{ sport.sport_name }}</h2>
                                <a href="{% url 'sport:detail_not_user' sport.id%}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            </div>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {%endfor%}

                    <div class="col-sm-12">
                        <div class="col-sm-12 col-md-2">
                            <a href="{% url 'sport:register'%}">
                                <button type="button" class="btn btn-success">
                                    <span class="fas fa-registered"></span>&nbsp; Register
                                </button>
                            </a>
                        </div>
                        
                        <div class="col-sm-12 col-md-9">
                            <a href="{% url 'sport:login_user'%}">
                                <button type="button" class="btn btn-success">
                                    <span class="glyphicon glyphicon-log-in"></span>&nbsp; Login
                                </button>
                            </a>
                        </div>   
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

sport/templates/sport/login.html
{% extends 'sport/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'sport:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Log In</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'sport:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}